### ISSUE TITLE
Update configuration

### ISSUE THREAD

**Issue by dbrekelmans** [dbrekelmans/domain-driven-bundle#1]
Update configuration to use the following structure and default values:
```
domain_driven:
    directories:
        context: '%kernel.project_dir%/src'
        application: 'Application'
        domain: 'Domain'
        infrastructure: 'Infrastructure'
        presentation: 'Presentation'
        config: 'config'
    files:
        routes: 'routes'
        services: 'services'
```
